#!/bin/bash

##############################################################
# This script checks if the Erding database responds to ping
##############################################################

STATE_OK=0
STATE_CRITICAL=2
STATE_UNKNOWN=3

COMMAND_RESULT=$(sudo -u oracle /usr/local/nagios/libexec/check_frontdb)
COMMAND_STATUS=$(echo $COMMAND_RESULT | wc -l)

case $((COMMAND_STATUS)) in
	1)
		echo "PING OK: $( echo $COMMAND_RESULT | sed -e "s/^OK (\([^)]*\))/\1/")"
		exit $STATE_OK
		;;
	0)
		echo "PING FAILED"
		exit $STATE_CRITICAL
		;;
	*)
		echo "Unknown state"
		exit $STATE_UNKNOWN
esac
