#!/bin/bash

vcountsession=0
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2

vcountsession=$(sudo -u oracle /usr/local/nagios/libexec/check_active_session_front)

if [ $vcountsession -ge 50 ]; then
echo "SESSIONS CRITICAL: $vcountsession sesiones activas"
exit $STATE_CRITICAL

else 
      if [ $vcountsession -ge 25 ]; then
      echo "SESSIONS WARNING: $vcountsession sesiones activas"
      exit $STATE_WARNING

      else
          echo "SESSIONS OK: $vcountsession sesiones activas"
          exit $STATE_OK
      fi
fi
