#!/bin/bash

if [ "$USER" != "oracle" ]; then
        echo "Error!! only execute as oracle!"
        exit 1
fi

. /home/oracle/.bash_profile 2>/dev/null
$ORACLE_HOME/bin/sqlplus -s system/v3ranit0by3 @/usr/local/nagios/libexec/check_active_session.sql
