#!/bin/bash

if [ "$USER" != "oracle" ]; then
        echo "Error!! only execute as oracle!"
        exit 1
fi

. /home/oracle/.bash_profile 2> /dev/null
$ORACLE_HOME/bin/tnsping RMBPRD | tail -1 | grep OK
