#!/bin/bash

DB=$1
PROFILE=""
PASS=""

if [ "$USER" != "oracle" ]; then
        echo "Error!! only execute as oracle!"
        exit 1
fi

if [ $DB = "front" ]; then
        PROFILE="/home/oracle/.bash_FRONTprofile"
	PASS="prdrmbw/mc3t1pdy35PM@FRONTPRD"
else
        PROFILE="/home/oracle/.bash_profile"
	PASS="system/v3ranit0by3"
fi

. $PROFILE 2>/dev/null
$ORACLE_HOME/bin/sqlplus -s $PASS @/usr/local/nagios/libexec/check_session.sql
