#!/bin/bash

DB=${1,,}
DISK=$2

if [ "$USER" != "oracle" ]; then
	echo "Error!! only execute as oracle!"
	exit 1
fi

if [ -z "$DISK" ]; then
	echo "No args specified."
	exit 1
fi


if [ $DB = "front" ]; then
        PROFILE="/home/oracle/.bash_FRONTprofile"
        PASS="prdrmbw/mc3t1pdy35PM@FRONTPRD"
elif [ $DB = "back" ]; then
        PROFILE="/home/oracle/.bash_profile"
        PASS="system/v3ranit0by3@PRDRBOPRD"
else
        PROFILE="/home/oracle/.bash_profileBMS"
        PASS="system/v3ranit0by3@BMSPRD"
fi

. $PROFILE 2>/dev/null
$ORACLE_HOME/bin/sqlplus -s $PASS @/usr/local/nagios/libexec/check_asm.sql $DISK || { echo ERROR ; exit 2; }
