#!/bin/bash

vcountsession=0
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2

WARNING=$1
CRITICAL=$2
DB="RUMPRD"
PMON=""

has_pmon(){
        if ps -fe | grep -v grep | grep -E "ora_pmon_$PMON" -q ; then
                return 0
        else
                return 1
        fi
}

HOST="$(echo $HOSTNAME | cut -d '.' -f1)"

if has_pmon ; then
	vcountsession=$(sudo -u oracle /usr/local/nagios/libexec/check_session $DB | sed -e "s/[^0-9]*\([0-9]*\)[^0-9]*/\1/")
else
        if [ "$HOST" = "madup01" ]; then
                HOST="madup02"
        else
                HOST="madup01"
        fi
	vcountsession=$(ssh $HOST sudo -u oracle /usr/local/nagios/libexec/check_session $DB | sed -e "s/[^0-9]*\([0-9]*\)[^0-9]*/\1/")
fi



if [ $vcountsession -ge $CRITICAL ]; then
	echo "SESSIONS CRITICAL: $vcountsession sesiones abiertas | sessions=$vcountsession;$WARNING;$CRITICAL"
	exit $STATE_CRITICAL
else 
	if [ $vcountsession -ge $WARNING ]; then
		echo "SESSIONS WARNING: $vcountsession sesiones abiertas | sessions=$vcountsession;$WARNING;$CRITICAL"
		exit $STATE_WARNING
	else
		echo "SESSIONS OK: $vcountsession sesiones abiertas | sessions=$vcountsession;$WARNING;$CRITICAL"
		exit $STATE_OK
      fi
fi
