#!/bin/bash

DB=$1
TABLESPACE=$2
PASS=""
PROFILE=""

if [ "$USER" != "oracle" ]; then
	echo "Error!! only execute as oracle!"
	exit 1
fi

if [ -z "$TABLESPACE" ]; then
	echo "No args specified."
	exit 1
fi

if [ $DB = "front" ]; then
        PROFILE="/home/oracle/.bash_FRONTprofile"
	BLOCKSIZE="8192"
	PASS="prdrmbw/mc3t1pdy35PM@FRONTPRD"
elif [ $DB = "back" ]; then
        PROFILE="/home/oracle/.bash_profile"
	BLOCKSIZE="4096"
	PASS="system/v3ranit0by3@PRDRBOPRD"
else
        PROFILE="/home/oracle/.bash_profileBMS"
	BLOCKSIZE="8192"
	PASS="system/v3ranit0by3@BMSPRD"
fi

. $PROFILE 2>/dev/null
$ORACLE_HOME/bin/sqlplus -s $PASS << SQLSCRIPT
set pagesize 0
set heading off
set feedback off

select TSFREE, TAM_MAX, (TAM_ACT/TAM_MAX)*100 as PCT_USED from (
                        select tablespace_name, TAM_MAX - TAM_ACT as TSFREE, TAM_ACT, TAM_MAX from (
                                select tablespace_name, sum((bytes/1024)/1024) as TAM_ACT, sum((maxbytes/1024)/1024) as TAM_MAX
                                from dba_data_files where tablespace_name not like 'UNDO%' and AUTOEXTENSIBLE='YES' group by tablespace_name)
                        a where a.tablespace_name='$TABLESPACE') where tablespace_name='$TABLESPACE';

exit;
SQLSCRIPT
